In [1]:
import pandas as pd
df:pd.DataFrame = pd.read_csv("step5.csv")
df

,floor,kitchen_area,living_area,rooms,is_apartment,studio,total_area,build_year,building_type_int,latitude,longitude,ceiling_height,flats_count,floors_total,has_elevator,target
0,9,9.90,19.900000,1,0,0,35.099998,1965,6,55.717113,37.781120,2.64,84,12,1,9500000
1,7,0.00,16.600000,1,0,0,43.000000,2001,2,55.794849,37.608013,3.00,97,10,1,13500000
2,9,9.00,32.000000,2,0,0,56.000000,2000,4,55.740040,37.761742,2.70,80,10,1,13500000
3,3,3.00,14.000000,1,0,0,24.000000,1971,1,55.808807,37.707306,2.60,208,9,1,5200000
4,9,0.00,0.000000,2,0,0,51.009998,2017,4,55.724728,37.743069,2.70,192,17,1,8490104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110329,8,6.00,42.000000,3,0,0,64.000000,1971,4,55.740402,37.834579,2.64,428,9,1,10800000
110330,5,5.28,28.330000,2,0,0,41.110001,1960,1,55.727470,37.768677,2.48,80,5,0,7400000
110331,7,5.30,20.000000,1,0,0,31.500000,1966,4,55.704315,37.506584,2.64,72,9,1,9700000
110332,15,13.80,33.700001,2,0,0,65.300003,2017,4,55.699863,37.939564,2.70,480,25,1,11750000
110333,16,7.60,18.000000,1,0,0,38.000000,1988,4,55.862133,37.689613,2.74,128,17,1,8000000

In [2]:
df.nsmallest(5, "target")

,floor,kitchen_area,living_area,rooms,is_apartment,studio,total_area,build_year,building_type_int,latitude,longitude,ceiling_height,flats_count,floors_total,has_elevator,target
33622,5,6.0,0.0,1,0,0,16.000000,1980,4,55.618031,37.605957,2.70,127,22,1,1500000
67338,3,0.0,30.0,1,0,0,35.000000,2019,2,55.567467,37.490234,2.85,187,6,1,1500000
61823,3,8.0,55.0,3,0,0,63.000000,1965,6,55.681026,37.545979,2.64,72,5,1,1530000
47960,8,9.0,26.0,1,0,0,41.000000,1928,1,55.740913,37.547558,3.00,48,8,0,1650000
62265,8,10.0,16.0,1,0,0,39.599998,2016,2,55.736511,37.412640,2.70,256,17,1,1700000